# Generated by Django 2.2.5 on 2020-04-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullName',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='positiion',
            new_name='position',
        ),
    ]
