# Generated by Django 2.2.5 on 2020-04-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20200427_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullname',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='positiion',
        ),
    ]
